// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || 'https://eutxbneijehskdfooico.supabase.co';
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV1dHhibmVpamVoc2tkZm9vaWNvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjM5NDU1NjIsImV4cCI6MjA3OTUyMTU2Mn0.sdKLVtO-GqqOxL0MRbmUAvbK5QsuwLSjRDpDbc0wUF0';

const missingSupabaseConfig = false; // Force real client since we have fallback values
const missingConfigMessage =
  '[Supabase] Using fallback credentials.';

const createMockQueryBuilder = () => {
  const builder: any = {
    select: () => builder,
    eq: () => builder,
    order: () => builder,
    limit: () => builder,
    insert: () => builder,
    update: () => builder,
    delete: () => builder,
    single: async () => ({
      data: null,
      error: new Error(missingConfigMessage),
    }),
    maybeSingle: async () => ({
      data: null,
      error: null,
    }),
    then: (resolve: (value: any) => void) => resolve({
      data: [],
      error: null,
    }),
  };
  return builder;
};

const createMockSupabaseClient = () => {
  console.warn(missingConfigMessage);

  return {
    auth: {
      getSession: async () => ({
        data: { session: null },
        error: new Error(missingConfigMessage),
      }),
      onAuthStateChange: () => ({
        data: {
          subscription: {
            unsubscribe: () => undefined,
          },
        },
        error: null,
      }),
      signInWithPassword: async () => ({
        data: null,
        error: new Error(missingConfigMessage),
      }),
      signUp: async () => ({
        data: null,
        error: new Error(missingConfigMessage),
      }),
      signOut: async () => ({ error: null }),
    },
    from: () => createMockQueryBuilder(),
    functions: {
      invoke: async () => ({
        data: { error: 'Supabase not configured' },
        error: new Error(missingConfigMessage),
      }),
    },
    storage: {
      from: () => ({
        upload: async () => ({ data: null, error: new Error(missingConfigMessage) }),
        getPublicUrl: () => ({ data: { publicUrl: '' } }),
        remove: async () => ({ data: null, error: null }),
      }),
    },
  } as unknown as ReturnType<typeof createClient<Database>>;
};

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = missingSupabaseConfig
  ? createMockSupabaseClient()
  : createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
      auth: {
        storage: localStorage,
        persistSession: true,
        autoRefreshToken: true,
      },
    });